import type { ContentPack } from '../domain/content/types';
import type { PracticeSession } from '../domain/practice/types';
import { progressMetrics } from '../domain/progress/metrics';
import { summarize } from '../domain/practice/summary';
import { isActive } from '../domain/practice/session';
import { Revision } from './Revision';
import type { RevisionItem } from '../domain/practice/revision';
export function Progress({ pack, sessions, onView, onRevision }: { pack: ContentPack; sessions: PracticeSession[]; onView: (id: string) => void; onRevision: (items: RevisionItem[]) => void }) {
  const metrics = progressMetrics(pack, sessions);
  const active = sessions.find(isActive);
  return <>
    <div className="overview"><div className="stat-card"><div><strong>{metrics.completed.filter(item => item.mode !== 'revision').length}</strong><span>Completed practice sessions</span></div></div><div className="stat-card"><div><strong>{metrics.completed.filter(item => item.mode === 'revision').length}</strong><span>Completed revision runs</span></div></div><div className="stat-card"><div><strong>{metrics.pending.length}</strong><span>Items awaiting revision</span></div></div></div>
    {active && <section className="empty-state"><h2>Continue your saved run</h2><p>{active.attempts.length} / {active.order.length} answers checked</p><button onClick={() => onView(active.sessionId)}>Resume practice</button></section>}
    <Revision items={metrics.pending} onStart={onRevision} />
    <section className="empty-state"><h2>Block coverage</h2><p>Unique questions in completed practice runs. Scores below use the latest first attempt for each current question. Revision does not replace these scores.</p>{metrics.blocks.map(item => <div key={item.blockId}><h3>{item.label}</h3><progress value={item.answered} max={item.total} aria-label={`${item.label} question coverage`} /><p>{item.answered} / {item.total} questions covered · {item.unaided} unaided correct · {item.pending} pending revision</p></div>)}</section>
    <section className="empty-state"><h2>Construction & theme progress</h2>{metrics.themes.map(theme => <section key={theme.label}><h3>{theme.label}</h3><p>{theme.answered} / {theme.total} questions covered · {theme.unaided} unaided correct</p><ul className="type-breakdown">{metrics.constructions.filter(item => item.theme === theme.label).map(item => <li key={item.entryId}><span lang="de">{item.label}</span><span>{item.answered}/{item.total} covered · {item.unaided} unaided · {item.pending} pending</span></li>)}</ul></section>)}</section>
    <section className="empty-state"><h2>Recent sessions</h2><p>Latest 20 runs are shown; all saved runs remain in your backup. Incomplete and abandoned runs have no final score.</p>{sessions.length ? <ul className="review-list">{[...sessions].sort((a, b) => b.startedAt.localeCompare(a.startedAt)).slice(0, 20).map(session => { const score = summarize(session); const archived = session.packId !== pack.packId || session.contentSnapshot.questions.some(question => !pack.questions.some(current => current.id === question.id && current.revision === question.revision)); return <li key={session.sessionId}><div><strong>{session.mode === 'revision' ? 'Revision' : session.mode === 'quick' ? 'Quick Practice' : 'Standard Practice'} · {session.order.length} questions</strong><p>{new Date(session.startedAt).toLocaleString()} · {session.status}{archived ? ' · Archived content' : ''}</p><p>{score.accuracy === null ? `${score.answered} checked; no final score` : `${Math.round(score.accuracy * 100)}% unaided correct · ${score.wrong} wrong · ${score.assisted} assisted`}</p></div>{session.status !== 'abandoned' && <button className="quiet-button" onClick={() => onView(session.sessionId)}>{isActive(session) ? 'Resume run' : 'View saved summary'}</button>}</li>; })}</ul> : <p>No saved sessions yet. Learn remains ungraded.</p>}</section>
  </>;
}
